# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 527b9ebd6e73a8bff31aeffbe7c4031b23c09c2aaacc65e87775c9af2e697f5af962a6bc238e130584ff973a283251a998ec1e5a06b53d8cd012b99eddc26c3d

test:
  secret_key_base: 029160879105c4835ee782fd4d586e5318c0bad0ac458999cf6b6a21c641f0034a580121252bbc32bf6608b6aac16a88c1fe793aaa1d7ebcf7146c86f2fdfd57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
